replicaCount: 1

image:
  repository: nginxdemos/hello
  tag: latest
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: LoadBalancer
  port: 80

env:
  - name: ENVIRONMENT
    value: "dev"
  - name: SECRET_VALUE
    valueFrom:
      secretKeyRef:
        name: hello-app-secret-dev
        key: secretValue
