name: Deploy Application

on:
  repository_dispatch:
    types: [infra-deployed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install AWS CLI
      run: |
        sudo apt-get install -y awscli

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --name eks-eurasia --region us-east-1
        
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.8.1'

    - name: Install Helmfile
      run: |
        wget -O helmfile https://github.com/roboll/helmfile/releases/download/v0.144.0/helmfile_linux_amd64
        chmod +x helmfile
        sudo mv helmfile /usr/local/bin/

    - name: Install Helm Diff Plugin
      run: |
        helm plugin install https://github.com/databus23/helm-diff

    - name: Verify Helm Plugins
      run: |
        helm plugin list

    - name: Deploy to Dev
      run: |
        cd app
        helmfile -e dev apply

    - name: Deploy to Stage
      run: |
        cd app
        helmfile -e stage apply
